version: '3'
services:
  app: &app
    build: .
    environment:
      - PYTHONPATH=/usr/src/app
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
    networks:
      - ns

  redis:
    image: redis:5.0.7
    networks:
      - ns

  format:
    <<: *app
    command: black --target-version py37 nono
    depends_on: []

  style:
    <<: *app
    command: black --target-version py37 --check nono
    depends_on: []

  complexity:
    <<: *app
    command: xenon --ignore "tests" --max-absolute A --max-modules A --max-average A nono
    working_dir: /usr/src/app/nono
    depends_on: []

  test:
    <<: *app
    command: pytest -s nono
    depends_on: []

  security-sast:
    <<: *app
    command: bandit -r nono -x test
    depends_on: []

  type:
    <<: *app
    command: mypy nono --ignore-missing-import
    depends_on: []

networks:
  ns:
    external:
      name: my-network
